server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: optional:file:.env[.properties]
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/users/**

        - id: goal-service
          uri: ${GOAL_SERVICE_URL}
          predicates:
            - Path=/goals/**

        - id: finance-service
          uri: ${FINANCE_SERVICE_URL}
          predicates:
            - Path=/finance/**

        - id: analytics-service
          uri: ${ANALYTICS_SERVICE_URL}
          predicates:
            - Path=/analytics/**

        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URL}
          predicates:
            - Path=/notifications/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.cloud.gateway: INFO
    sdu.diploma: DEBUG
